// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using YoutubeBulkUploader.Web.Data;

#nullable disable

namespace YoutubeBulkUploader.Web.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260715000442_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("YoutubeBulkUploader.Web.Models.DataStoreEntry", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("ValueProtected")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.HasKey("Key");

                    b.ToTable("DataStoreEntries");
                });

            modelBuilder.Entity("YoutubeBulkUploader.Web.Models.OAuthClientConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("ClientIdProtected")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("ClientSecretProtected")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<string>("ConnectedChannelTitle")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("OAuthClientConfigs");
                });

            modelBuilder.Entity("YoutubeBulkUploader.Web.Models.UploadJob", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Privacy")
                        .HasColumnType("INTEGER");

                    b.Property<double>("ProgressPercent")
                        .HasColumnType("REAL");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("YouTubeVideoId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("UploadJobs");
                });
#pragma warning restore 612, 618
        }
    }
}
